#%RAML 0.8
title: OICLed
version: v1.0-20151126
schemas:
  - Led: !include oic.r.led.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a"]

/LedResURI:
  description: |
    This resource describes a LED (on/off).
    The value is a boolean.
    A value of 'true' means that the led is on.
    A value of 'false' means that the led is off.
  displayName: Led
  is: [ interface ] # valid for all methods

  get:
    responses:
      200:
        body:
          application/json:
            schema: Led
            example: |
              {
                "rt":     "oic.r.led",
                "id":     "unique_example_id",
                "value":  false
              }
  post:
    body:
      application/json:
        schema: Led
        example: |
          {
            "id":    "unique_example_id",
            "value": true
          }
    responses:
      200:
        body:
          application/json:
            schema: Led
            example: |
              {
                "rt":    "oic.r.led",
                "id":    "unique_example_id",
                "value": true
              }
