ocserver: ocserver.cpp
	g++ -o ocserver -std=c++11 -pthread -lmraa -loctbstack -I/usr/include/iotivity/resource/stack/ -I/usr/include/iotivity/resource/logger/ \
	-I/usr/include/iotivity/resource/oc_logger/  ocserver.cpp

