#%RAML 0.8
title: OICFan
version: v1.0-20151126
schemas:
  - Fan: !include oic.r.fan.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a"]

/FanResURI:
  description: |
    This resource describes a fan (on/off).
    The value is a boolean.
    A value of 'true' means that the fan is on.
    A value of 'false' means that the fan is off.
  displayName: Fan
  is: [ interface ] # valid for all methods

  get:
    responses:
      200:
        body:
          application/json:
            schema: Fan
            example: |
              {
                "rt":     "oic.r.fan",
                "id":     "unique_example_id",
                "value":  false
              }
  post:
    body:
      application/json:
        schema: Fan
        example: |
          {
            "id":    "unique_example_id",
            "value": true
          }
    responses:
      200:
        body:
          application/json:
            schema: Fan
            example: |
              {
                "rt":     "oic.r.fan",
                "id":    "unique_example_id",
                "value": true
              }
